// Monday Leads Export 5.8.2026 - Parsed Property Data
// This file contains all leads from the Monday export for bulk import

export interface LeadData {
  name: string
  parkNames: string[]
  city: string
  state: string
  address: string
  totalLots: number
  price: number | null
  pricePerPad: number | null
  lotRent: number | null
  medianHomePrice: number | null
  toh: number | null
  poh: number | null
  vacant: number | null
  avgRent2br: number | null
  avgRent3br: number | null
  notes: string
  email: string | null
  source: string
}

export const MONDAY_LEADS: LeadData[] = [
  // MAIN LISTINGS
  { name: "Crestview MHC", parkNames: ["Crestview MHC"], city: "Concord", state: "NC", address: "3715 Patricia Drive NW, Concord, NC 28027", totalLots: 0, price: null, pricePerPad: null, lotRent: null, medianHomePrice: null, toh: null, poh: null, vacant: null, avgRent2br: 1400, avgRent3br: 1700, notes: "Minimal info. Address only.", email: null, source: "Monday Leads" },
  { name: "Shady Acres MHC", parkNames: ["Shady Acres"], city: "Knightdale", state: "NC", address: "104 Shady Cir, Knightdale, NC", totalLots: 0, price: null, pricePerPad: null, lotRent: null, medianHomePrice: null, toh: null, poh: null, vacant: null, avgRent2br: 1350, avgRent3br: 1650, notes: "Minimal info. Address only.", email: null, source: "Monday Leads" },
  { name: "Green Hills Mobile Home Park", parkNames: ["Green Hills Mobile Home Park"], city: "Old Hickory", state: "TN", address: "14200 Lebanon Rd, Old Hickory, TN 37138", totalLots: 0, price: null, pricePerPad: null, lotRent: null, medianHomePrice: null, toh: null, poh: null, vacant: null, avgRent2br: 1200, avgRent3br: 1450, notes: "Minimal info. Address only.", email: null, source: "Monday Leads" },
  { name: "Webster's Crossing Mobile Home Park", parkNames: ["Webster's Crossing Mobile Home Park"], city: "Auburn", state: "AL", address: "425 Webster Rd, Auburn, AL", totalLots: 126, price: 20000000, pricePerPad: 373667, lotRent: null, medianHomePrice: null, toh: null, poh: 53, vacant: null, avgRent2br: null, avgRent3br: null, notes: "Owner attorney: Patrick C. Davidson. Sellers firm at $20M. ~$4M capital gains hit. Median income: $42,717.", email: "rick@davidsonumbach.com", source: "Monday Leads" },
  { name: "Cedar Grove Manufactured Home Community", parkNames: ["Cedar Grove Manufactured Home Community"], city: "Copperas Cove", state: "TX", address: "100 Cedar Grove Dr, Copperas Cove, TX", totalLots: 675, price: 80000000, pricePerPad: 118519, lotRent: 300, medianHomePrice: 223474, toh: 67, poh: 608, vacant: 0, avgRent2br: 950, avgRent3br: 1150, notes: "675 total spaces. ~90% POH, ~10% TOH. Year built: 1965. Median income: $70,629.", email: null, source: "Monday Leads" },
  { name: "East Garden Village", parkNames: ["East Garden Village"], city: "Garden City", state: "KS", address: "4101 E US Hwy 50, Garden City, KS 67846", totalLots: 634, price: null, pricePerPad: null, lotRent: null, medianHomePrice: null, toh: 430, poh: null, vacant: 204, avgRent2br: null, avgRent3br: null, notes: "All TOHs. 430 occupied. City water/sewer, direct billed. Owner: Rob Martin.", email: "egv@wkh-llc.com", source: "Monday Leads" },
  { name: "Lake Powell Mobile Home Village", parkNames: ["Lake Powell Mobile Home Village", "Chapman Mobile Home Park"], city: "Page", state: "AZ", address: "606 lots total", totalLots: 606, price: 39000000, pricePerPad: 64356, lotRent: 582, medianHomePrice: 373119, toh: 556, poh: null, vacant: 50, avgRent2br: null, avgRent3br: null, notes: "2-park portfolio. Lake Powell MHV: 452 lots. Chapman MHP: 154 lots. Median income: $83,299.", email: null, source: "Monday Leads" },
  { name: "Parkview MHP", parkNames: ["Parkview MHP"], city: "Green Bay", state: "WI", address: "1331 Bellevue St, Green Bay, WI", totalLots: 510, price: null, pricePerPad: null, lotRent: 350, medianHomePrice: 230384, toh: 510, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "510 lots, 100% occupied, all TOH. Lot rent $350/mo + $20 for 2-stall garage. Multiple owners. Median income: $55,772.", email: null, source: "Monday Leads" },
  { name: "Bali Hai Estates", parkNames: ["Bali Hai Estates"], city: "Hiawatha", state: "IA", address: "1405 Robins Road, Hiawatha, IA", totalLots: 430, price: 35000000, pricePerPad: 81395, lotRent: 395, medianHomePrice: 256432, toh: 387, poh: null, vacant: 43, avgRent2br: null, avgRent3br: null, notes: "430 spaces, 90% occupancy. All TOH. 150 acres. Asking price $35M. Median income: $66,497.", email: null, source: "Monday Leads" },
  { name: "Harston Wood Manufactured Home Community", parkNames: ["Harston Wood Manufactured Home Community"], city: "Euless", state: "TX", address: "10920 Harston Woods Dr, Euless, TX", totalLots: 423, price: null, pricePerPad: null, lotRent: 733, medianHomePrice: 208716, toh: 352, poh: null, vacant: 71, avgRent2br: null, avgRent3br: null, notes: "423 total lots, 71 vacant. All TOH. Avg lot rent $733. Median income: $65,132.", email: null, source: "Monday Leads" },
  { name: "Westbrook Village", parkNames: ["Westbrook Village"], city: "Noblesville", state: "IN", address: "17301 River Avenue, Noblesville, IN", totalLots: 410, price: null, pricePerPad: null, lotRent: 405, medianHomePrice: 429188, toh: 410, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "410 total lots, all occupied, all TOH. Lot rent $400-$410/mo. Median income: $120,100.", email: null, source: "Monday Leads" },
  { name: "Cedar Heights Mobile Home Park", parkNames: ["Cedar Heights Mobile Home Park"], city: "Louisville", state: "KY", address: "7600 Heights Dr, Louisville, KY 40291", totalLots: 393, price: null, pricePerPad: null, lotRent: 500, medianHomePrice: 253000, toh: null, poh: null, vacant: 3, avgRent2br: 1100, avgRent3br: 1350, notes: "Owner: Judy Allen. ~50-60 acres. City water/sewer. SW lot rent $500, DW $600. POH RTO ~$1,300/mo.", email: null, source: "Monday Leads" },
  { name: "Troy Villa Community", parkNames: ["Troy Villa Community"], city: "Perrysburg", state: "OH", address: "3561 Truman Rd, Perrysburg, OH", totalLots: 330, price: 20000000, pricePerPad: 60606, lotRent: 430, medianHomePrice: 326254, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "330 lots, mix of TOH and POH. ~50% vacant. Asking ~$20M. Median income: $95,846.", email: "nathan@freeholdre.com", source: "Monday Leads" },
  { name: "Eastview Mobile Home Park", parkNames: ["Eastview Mobile Home Park"], city: "Annandale", state: "MN", address: "60-B Sycamore St, Annandale, MN", totalLots: 305, price: null, pricePerPad: null, lotRent: 350, medianHomePrice: 393917, toh: 267, poh: null, vacant: 38, avgRent2br: null, avgRent3br: null, notes: "305 lots, all TOH, 267 occupied. Lot rent $350/mo. Marvin (owner, 89 yrs old). Median income: $78,194.", email: "emhpannandale@gmail.com", source: "Monday Leads" },
  { name: "Oak Crest Pointe MHC", parkNames: ["Oak Crest Pointe MHC"], city: "San Antonio", state: "TX", address: "6435 Crestway Dr, San Antonio, TX", totalLots: 304, price: null, pricePerPad: null, lotRent: 638, medianHomePrice: 215439, toh: 274, poh: null, vacant: 2, avgRent2br: null, avgRent3br: null, notes: "304 lots, 302 occupied. ~90% TOH. Lot rent $628-$648. Owner William T Connell, 90 years old. Median income: $70,098.", email: "oakcrestpointe@gmail.com", source: "Monday Leads" },
  { name: "Lake Pan RV Village", parkNames: ["Lake Pan RV Village", "Tarpon Lakeview Mobile Home Park"], city: "Lake Panasoffkee", state: "FL", address: "190 NW 4th Dr, Lake Panasoffkee, FL 33538", totalLots: 303, price: 27000000, pricePerPad: 89109, lotRent: null, medianHomePrice: 209000, toh: null, poh: null, vacant: 2, avgRent2br: null, avgRent3br: null, notes: "2-park portfolio. Lake Pan: 138 sites, asking $7.2M. Tarpon: 165 sites, asking $20M.", email: null, source: "Monday Leads" },
  { name: "Friendly Village", parkNames: ["Friendly Village"], city: "Tucson", state: "AZ", address: "101 West River Road, Tucson, AZ", totalLots: 295, price: null, pricePerPad: null, lotRent: 657, medianHomePrice: 447090, toh: 295, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "295 total lots, 100% occupied, all TOH. Lot rent $657/mo. Median income: $76,915.", email: null, source: "Monday Leads" },
  { name: "Stadium MHP", parkNames: ["Stadium MHP"], city: "Key West", state: "FL", address: "1213 14th St, Key West, FL", totalLots: 278, price: null, pricePerPad: null, lotRent: 1485, medianHomePrice: 945625, toh: 272, poh: null, vacant: 6, avgRent2br: null, avgRent3br: null, notes: "278 total lots, 98% occupied. All TOH. Lot rent $1,485/mo. Median income: $86,586.", email: null, source: "Monday Leads" },
  { name: "Colony Mobile Home Park", parkNames: ["Colony Mobile Home Park"], city: "Virginia Beach", state: "VA", address: "913 Virginia Beach Blvd, Virginia Beach, VA", totalLots: 240, price: 60000000, pricePerPad: 250000, lotRent: 963, medianHomePrice: 637291, toh: 220, poh: null, vacant: 20, avgRent2br: 1600, avgRent3br: 2000, notes: "240 spaces, 220 rented. All TOH. Lot rent $925-$1,000/mo. Family-owned 75-80 years. Firm at $60M. Median income: $97,945.", email: "wchaplain1@gmail.com", source: "Monday Leads" },
  { name: "Sunrise Village Active 55+ Community", parkNames: ["Sunrise Village Active 55+ Community"], city: "Mesa", state: "AZ", address: "5402 E. Mckellips Rd, Mesa, AZ 85215", totalLots: 230, price: null, pricePerPad: null, lotRent: 835, medianHomePrice: 530000, toh: 217, poh: 13, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "55+ community. 217 occupied TOHs + 13 vacant POHs for sale/RTO. Lot rent $835-$851.", email: null, source: "Monday Leads" },
  { name: "Urban Village MHP", parkNames: ["Urban Village MHP", "Knob Hill Mobile Home Park"], city: "Boonville", state: "IN", address: "398 Lark Ln, Boonville, IN", totalLots: 226, price: null, pricePerPad: null, lotRent: 390, medianHomePrice: 268514, toh: 218, poh: null, vacant: 8, avgRent2br: 750, avgRent3br: 900, notes: "2-park portfolio. Urban Village: 98 lots, 60 occupied. Knob Hill: 128 lots, 8 vacant.", email: "howardwells911@gmail.com", source: "Monday Leads" },
  { name: "Oakwood Campsite", parkNames: ["Oakwood Campsite"], city: "Wild Rose", state: "WI", address: "N5428 24th Ave, Wild Rose, WI 54984", totalLots: 215, price: 4250000, pricePerPad: 19767, lotRent: 400, medianHomePrice: 180000, toh: 65, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "65 MH lots + 150 seasonal campsites. Owner asking $4.25-4.5M.", email: null, source: "Monday Leads" },
  { name: "Riviera Mobile Home Park", parkNames: ["Riviera Mobile Home Park"], city: "Scottsdale", state: "AZ", address: "601 North Hayden Road, Scottsdale, AZ", totalLots: 210, price: null, pricePerPad: null, lotRent: 610, medianHomePrice: 551859, toh: 210, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "210 total spaces, 100% occupied, all TOH. Lot rent $595-$625/mo. Median income: $86,962.", email: null, source: "Monday Leads" },
  { name: "Homestead Park", parkNames: ["Homestead Park"], city: "Columbus", state: "IN", address: "2667 Milmar Court, Columbus, IN", totalLots: 188, price: null, pricePerPad: null, lotRent: 310, medianHomePrice: 282274, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "", email: "ddoup@tbcci.com", source: "Monday Leads" },
  { name: "Palm Terrace", parkNames: ["Palm Terrace"], city: "Bunnell", state: "FL", address: "2250 Old Moody Blvd #16, Bunnell, FL", totalLots: 182, price: null, pricePerPad: null, lotRent: 413, medianHomePrice: 296289, toh: 179, poh: null, vacant: 3, avgRent2br: null, avgRent3br: null, notes: "182 total spaces: 135 MH + 47 RV. MH lot rent $375/mo, RV $500/mo. Not interested in selling.", email: "gjlorbeck@aol.com", source: "Monday Leads" },
  { name: "Country Club Estates MHP", parkNames: ["Country Club Estates MHP", "Spring River RV Park"], city: "Artesia", state: "NM", address: "401 N 26th St, Artesia, NM", totalLots: 180, price: 3000000, pricePerPad: 16667, lotRent: 388, medianHomePrice: 227221, toh: 105, poh: null, vacant: 0, avgRent2br: 1500, avgRent3br: 1800, notes: "2-park portfolio. Owner: Robert Ronald Amador. 6 parks total. Spring River asking ~$3M.", email: "enchantedmesa65@gmail.com", source: "Monday Leads" },
  { name: "Fairhaven Mobile Home Park", parkNames: ["Fairhaven Mobile Home Park"], city: "St. Petersburg", state: "FL", address: "5757 66th St N, St. Petersburg, FL 33709", totalLots: 180, price: null, pricePerPad: null, lotRent: 640, medianHomePrice: 263000, toh: 176, poh: null, vacant: 4, avgRent2br: 800, avgRent3br: 950, notes: "All TOH. City water/sewer. Owner turned down $22M offer.", email: null, source: "Monday Leads" },
  { name: "Hillview Mobile Home Court", parkNames: ["Hillview Mobile Home Court"], city: "Brownstown", state: "IN", address: "420 S Asher St, Brownstown, IN 47220", totalLots: 173, price: null, pricePerPad: null, lotRent: 350, medianHomePrice: 241000, toh: 120, poh: null, vacant: 53, avgRent2br: null, avgRent3br: null, notes: "Owner: Sharon Smith Wills. 120 occupied, 80% TOH / 20% POH. POH rent $1,000-$1,200.", email: "lawills@bright.net", source: "Monday Leads" },
  { name: "Avalon MHP", parkNames: ["Avalon MHP", "Greenhill Estates Mobile Home"], city: "Kennedale", state: "TX", address: "520 North Rd, Kennedale, TX", totalLots: 170, price: null, pricePerPad: null, lotRent: 635, medianHomePrice: null, toh: 170, poh: null, vacant: 9, avgRent2br: null, avgRent3br: null, notes: "2-park portfolio. Avalon: 98 lots. Greenhill: 72 lots, 100% occupied.", email: "grjones@flash.net", source: "Monday Leads" },
  { name: "Lake Arlington Ranch", parkNames: ["Lake Arlington Ranch"], city: "Fort Worth", state: "TX", address: "5137 Big Fork Drive, Fort Worth, TX", totalLots: 170, price: 34000000, pricePerPad: 200000, lotRent: 700, medianHomePrice: 192694, toh: 170, poh: null, vacant: 0, avgRent2br: 1700, avgRent3br: null, notes: "170 lots, all occupied, all TOH. Lot rent $700/mo. ~$2M in home notes. Asking $200K/pad. Median income: $46,537.", email: "vinsumerlin@yahoo.com", source: "Monday Leads" },
  { name: "Meadows Mobile Home Park", parkNames: ["Meadows Mobile Home Park"], city: "Mountain Home", state: "ID", address: "1075 W 6th S St, Mountain Home, ID", totalLots: 163, price: 13000000, pricePerPad: 79755, lotRent: 550, medianHomePrice: 349185, toh: 83, poh: 80, vacant: 0, avgRent2br: 800, avgRent3br: 950, notes: "163 lots: 80 POH, 83 TOH. Lot rent $550 + utilities. POH rent $850-$1,250. Asking $13M. Median income: $57,769.", email: "cblack@newmarkmw.com", source: "Monday Leads" },
  { name: "Suburban Estates MHP", parkNames: ["Suburban Estates MHP"], city: "Noblesville", state: "IN", address: "3288 Cicero Rd, Noblesville, IN", totalLots: 151, price: null, pricePerPad: null, lotRent: 435, medianHomePrice: 349778, toh: 148, poh: null, vacant: 3, avgRent2br: null, avgRent3br: null, notes: "151 lots, 3 vacant, all TOH. Lot rent $435/mo. Turned down $11M offer. Median income: $91,918.", email: null, source: "Monday Leads" },
  { name: "Miami MHP", parkNames: ["Miami MHP"], city: "Miami", state: "FL", address: "939 NW 81st St, Miami, FL", totalLots: 150, price: 30000000, pricePerPad: 200000, lotRent: 850, medianHomePrice: 442038, toh: 150, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "150 total lots. All TOH. Lot rent $850/mo. Asking $30M firm.", email: null, source: "Monday Leads" },
  { name: "Jefferson Mobile Home Court", parkNames: ["Jefferson Mobile Home Court"], city: "Jeffersonville", state: "IN", address: "1800 Dutch Ln, Jeffersonville, IN", totalLots: 148, price: null, pricePerPad: null, lotRent: 303, medianHomePrice: 247515, toh: 148, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "148 lots, all occupied, all TOH. Lot rent $280-$325/mo. Owned since 1985. Median income: $70,290.", email: null, source: "Monday Leads" },
  { name: "El Retiro Mobile Home Park", parkNames: ["El Retiro Mobile Home Park"], city: "Miami", state: "FL", address: "3586 NW 41st St, Miami, FL", totalLots: 146, price: 26000000, pricePerPad: 178082, lotRent: 1000, medianHomePrice: null, toh: 146, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "146 lots, all occupied, all TOH. Lot rent $1,000+/mo. City requiring connection to city water ($1M-$1.5M). Asking $26M.", email: null, source: "Monday Leads" },
  { name: "Robbins Mobile Village", parkNames: ["Robbins Mobile Village"], city: "Waterford", state: "MI", address: "3300 Elizabeth Lake Rd, Waterford, MI", totalLots: 143, price: 7000000, pricePerPad: 48951, lotRent: 650, medianHomePrice: null, toh: 123, poh: 20, vacant: 12, avgRent2br: null, avgRent3br: null, notes: "143 spaces, 20 POH, ~12 vacants. Lot rent $650/mo. Asking $7M.", email: null, source: "Monday Leads" },
  { name: "Chubbuck Mobile Home Park", parkNames: ["Chubbuck Mobile Home Park"], city: "Pocatello", state: "ID", address: "210 Circle Inn Dr, Pocatello, ID", totalLots: 135, price: null, pricePerPad: null, lotRent: 395, medianHomePrice: 329887, toh: 121, poh: 14, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "135 lots, all occupied. 14 rent-to-own. Lot rent $395/mo. Plans to list through broker. Median income: $68,118.", email: "1hodgie@gmail.com", source: "Monday Leads" },
  { name: "Camptown Mobile Home Park", parkNames: ["Camptown Mobile Home Park"], city: "Show Low", state: "AZ", address: "1241 West McNeil, Show Low, AZ", totalLots: 122, price: 9000000, pricePerPad: 73770, lotRent: 550, medianHomePrice: 417407, toh: 116, poh: null, vacant: 6, avgRent2br: null, avgRent3br: null, notes: "122 total sites, ~95% occupied, all TOH. Lot rent $550/mo. Might sell for $9M. Median income: $60,313.", email: null, source: "Monday Leads" },
  { name: "Sullivan's Mobile Home Park", parkNames: ["Sullivan's Mobile Home Park"], city: "Eight Mile", state: "AL", address: "5925 US-45, Eight Mile, AL", totalLots: 120, price: 8000000, pricePerPad: 66667, lotRent: 350, medianHomePrice: 165085, toh: 80, poh: 40, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "120 spaces, all occupied. 80 TOH, 40 POH. Lot rent $350/mo. POH rent $1,000. Asking $8M. Median income: $49,317.", email: "jerryncathy@comcast.net", source: "Monday Leads" },
  { name: "Avilla Mobile Home Park", parkNames: ["Avilla Mobile Home Park"], city: "Avilla", state: "IN", address: "900 Autumn Hills Dr, Avilla, IN", totalLots: 115, price: 6000000, pricePerPad: 52174, lotRent: 300, medianHomePrice: 271037, toh: 50, poh: 65, vacant: 26, avgRent2br: null, avgRent3br: null, notes: "115 lots, 89 occupied. 65 POH, ~50 TOH. Lot rent $300/mo. POH rent $900-$1,200. Asking $6M. Median income: $84,408.", email: "steve.castleman@yahoo.com", source: "Monday Leads" },
  { name: "Mesa Grande Mobile Home Park", parkNames: ["Mesa Grande Mobile Home Park"], city: "Mesa", state: "AZ", address: "2912 East McKellips Road, Mesa, AZ", totalLots: 110, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 561659, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "110 lots. Median income: $100,671.", email: null, source: "Monday Leads" },
  { name: "Maplewood Village", parkNames: ["Maplewood Village"], city: "Appleton", state: "WI", address: "W3130 E. Broadway Drive, Appleton, WI", totalLots: 110, price: null, pricePerPad: null, lotRent: 395, medianHomePrice: 452440, toh: 110, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "110 lots + 1 SFH, all TOH. Lot rent $395. Previously owned 68-park portfolio. Median income: $103,149.", email: "rickrand@gvhinc.net", source: "Monday Leads" },
  { name: "Boise MHP", parkNames: ["Boise MHP"], city: "Boise", state: "ID", address: "2512 Barrington Ln, Boise, ID", totalLots: 102, price: 14280000, pricePerPad: 140000, lotRent: 400, medianHomePrice: 493000, toh: 75, poh: 26, vacant: 1, avgRent2br: null, avgRent3br: null, notes: "102 total lots, 1 vacant. 75 TOH, 26 POH. Lot rent $400/mo. Asking $140K/pad. Median income: $81,000.", email: null, source: "Monday Leads" },
  { name: "Key Allegro Villas", parkNames: ["Key Allegro Villas"], city: "Fairhope", state: "AL", address: "9528 Key W Dr, Fairhope, AL", totalLots: 97, price: 8500000, pricePerPad: 87629, lotRent: 345, medianHomePrice: 484432, toh: 93, poh: 4, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "97 spaces, all occupied. 4 POH, 93 TOH. Lot rent $345/mo increasing to $365. Asking $8.5M. Median income: $86,026.", email: "ddebourge@yahoo.com", source: "Monday Leads" },
  { name: "Southwood Village", parkNames: ["Southwood Village"], city: "Alabaster", state: "AL", address: "328 Cox Lane, Alabaster, AL", totalLots: 96, price: 7000000, pricePerPad: 72917, lotRent: null, medianHomePrice: null, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "96 mobile home spaces + 8 SFHs. Presented $7M all-cash offer. Plans to pass property to children.", email: null, source: "Monday Leads" },
  { name: "Beaverbrook Manor Mobile Home Park", parkNames: ["Beaverbrook Manor Mobile Home Park"], city: "Franklin", state: "VA", address: "2210 Elmwood Dr, Franklin, VA", totalLots: 92, price: 8000000, pricePerPad: 86957, lotRent: 363, medianHomePrice: 239233, toh: 52, poh: 40, vacant: 1, avgRent2br: 800, avgRent3br: 950, notes: "92 spaces, 1 vacant. 52 TOH, 40 POH. Lot rent $350-$375/mo. POH rent $850-$1,300. Asking $8M. Median income: $73,333.", email: "cjbryant57@verizon.net", source: "Monday Leads" },
  { name: "Bear Creek MHC", parkNames: ["Bear Creek"], city: "Douglas", state: "GA", address: "50 Bear Creek Road, Douglas, GA 31535", totalLots: 89, price: 3000000, pricePerPad: 33708, lotRent: 200, medianHomePrice: 165000, toh: 62, poh: 27, vacant: 3, avgRent2br: null, avgRent3br: null, notes: "89 total lots, 3 vacant. 27 POH, 62 TOH. Lot rent $200/mo.", email: null, source: "Monday Leads" },
  { name: "Coastal Homes of Topsail Island", parkNames: ["Coastal Homes of Topsail Island"], city: "Surf City", state: "NC", address: "164 Now Boys Loop, Surf City, NC", totalLots: 85, price: 11000000, pricePerPad: 129412, lotRent: 338, medianHomePrice: 520142, toh: 74, poh: 11, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "85 lots, fully occupied. 74 TOH, 11 POH. Lot rent ~$338/mo. Turned down $9M and $10M offers. Asking $11M. Median income: $84,016.", email: null, source: "Monday Leads" },
  { name: "Fair Meadows Estates", parkNames: ["Fair Meadows Estates"], city: "Hixson", state: "TN", address: "6225 Dayton Blvd, Hixson, TN", totalLots: 83, price: 1500000, pricePerPad: null, lotRent: null, medianHomePrice: 368506, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "83 lots. Median income: $79,177.", email: "p.schierholz@tsmmortgage.com", source: "Monday Leads" },
  { name: "Rol Park Village", parkNames: ["Rol Park Village"], city: "Millersville", state: "MD", address: "8049 Veterans Hwy, Millersville, MD 21108", totalLots: 82, price: null, pricePerPad: null, lotRent: 800, medianHomePrice: 618000, toh: 80, poh: null, vacant: 2, avgRent2br: 1400, avgRent3br: 1700, notes: "Owner: Gordon D Clement. 80 occupied. Lot rent $800/mo incl WST. Turned down $150K/pad (~$12M). Unlikely to sell.", email: "gordon@clementhardware.com", source: "Monday Leads" },
  { name: "Midway Manor Park", parkNames: ["Midway Manor Park"], city: "Leesburg", state: "FL", address: "36033 Emeralda Ave, Leesburg, FL", totalLots: 80, price: null, pricePerPad: null, lotRent: 300, medianHomePrice: 283211, toh: 80, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "80 lots, fully occupied, all TOH. Lot rent $300/mo. Not actively considering sale. Median income: $57,477.", email: "midwaymanor@gmail.com", source: "Monday Leads" },
  { name: "Belknap Terrace", parkNames: ["Belknap Terrace"], city: "Superior", state: "WI", address: "3556 Belknap St, Superior, WI 54880", totalLots: 79, price: null, pricePerPad: null, lotRent: 450, medianHomePrice: 219000, toh: 79, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "All occupied. 15 rent-to-own, rest TOH. City water/sewer.", email: null, source: "Monday Leads" },
  { name: "Lake Fox Village", parkNames: ["Lake Fox Village"], city: "Winter Haven", state: "FL", address: "317 Lakeview Ln SE, Winter Haven, FL 33884", totalLots: 77, price: 9250000, pricePerPad: null, lotRent: 570, medianHomePrice: 297000, toh: 77, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "All TOH, fully occupied. City water/sewer. Price $9.25M.", email: null, source: "Monday Leads" },
  { name: "Buffalo Run Mobile Home Park", parkNames: ["Buffalo Run Mobile Home Park"], city: "Camp Verde", state: "AZ", address: "2223 North Arena Del Loma, Camp Verde, AZ 86322", totalLots: 77, price: 5500000, pricePerPad: 71429, lotRent: 450, medianHomePrice: 350000, toh: 77, poh: null, vacant: 4, avgRent2br: null, avgRent3br: null, notes: "All TOH. Private water/sewer incl in rent. Asking $5M-$5.5M.", email: null, source: "Monday Leads" },
  { name: "Little River Mobile Home Park", parkNames: ["Little River Mobile Home Park"], city: "Miami", state: "FL", address: "215 NW 79th St, Miami, FL", totalLots: 76, price: 20000000, pricePerPad: 263158, lotRent: 870, medianHomePrice: 442038, toh: 76, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "76 lots, fully occupied, all TOH. Lot rent $740-$1,000/mo. Asking $20M firm. Median income: $40,802.", email: "cory@rentify.live", source: "Monday Leads" },
  { name: "Worldwide Park", parkNames: ["Worldwide Park"], city: "Lumberton", state: "TX", address: "207 S Lhs Dr, Lumberton, TX", totalLots: 76, price: 6080000, pricePerPad: 80000, lotRent: 395, medianHomePrice: 267167, toh: null, poh: null, vacant: 7, avgRent2br: null, avgRent3br: null, notes: "76 spaces, ~20-25 POH, ~6-8 vacant. Lot rent $395/mo. Pricing expectation ~$80K/pad. Median income: $93,225.", email: "wwwtwb@aol.com", source: "Monday Leads" },
  { name: "Oak Crest Mobile Park", parkNames: ["Oak Crest Mobile Park"], city: "Orlando", state: "FL", address: "5455 W Washington St, Orlando, FL", totalLots: 75, price: 6000000, pricePerPad: 80000, lotRent: 625, medianHomePrice: 197376, toh: 75, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "75 lots, fully occupied, all TOH. Lot rent $625/mo. Not motivated to sell. Offered $6M. Median income: $52,124.", email: "oak5455@aol.com", source: "Monday Leads" },
  { name: "Seven C's Community", parkNames: ["Seven C's Community"], city: "American Fork", state: "UT", address: "120 N 350 W St, American Fork, UT", totalLots: 74, price: 15000000, pricePerPad: 202703, lotRent: 800, medianHomePrice: 522208, toh: 74, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "74 sites, all occupied, all TOH. 55+ community. Lot rent $800/mo. Previously offered $15M. Median income: $95,823.", email: "dpriz@ymail.com", source: "Monday Leads" },
  { name: "Country Road Estates", parkNames: ["Country Road Estates"], city: "Galesville", state: "WI", address: "15454 Co Rd K, Galesville, WI", totalLots: 74, price: 5500000, pricePerPad: 74324, lotRent: 363, medianHomePrice: 311169, toh: 74, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "74 spaces, all occupied, all TOH. Lot rent $350-$375/mo. Asking $5-6M. Median income: $88,429.", email: "countryroadestates1@yahoo.com", source: "Monday Leads" },
  { name: "Suburbia Mobile Home Park", parkNames: ["Suburbia Mobile Home Park"], city: "Killeen", state: "TX", address: "5003 Saddle Ridge Dr, Killeen, TX", totalLots: 73, price: 6250000, pricePerPad: 85616, lotRent: 550, medianHomePrice: 217971, toh: 73, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "73 spaces, all occupied, all TOH. Lot rent $500-$600/mo. Asking $6M-$6.5M+. Median income: $62,536.", email: "linda@waco.twcbc.com", source: "Monday Leads" },
  { name: "Country Place Park", parkNames: ["Country Place Park"], city: "Mt Pleasant", state: "MI", address: "4151 E Jordan Rd, Mt Pleasant, MI", totalLots: 70, price: 2500000, pricePerPad: 35714, lotRent: 350, medianHomePrice: 212626, toh: 61, poh: 9, vacant: 4, avgRent2br: null, avgRent3br: null, notes: "70 spaces, 66 occupied. ~9 POH, ~61 TOH. Lot rent $350/mo. POH rent $700/mo. Asking $2.5M. Median income: $48,794.", email: "robertldidur@gmail.com", source: "Monday Leads" },
  { name: "Fox Creek MHP", parkNames: ["Fox Creek MHP", "Oakwood Park", "Durbin Creek MHC"], city: "Simpsonville", state: "SC", address: "491 Chapman Rd, Fountain Inn, SC 29644", totalLots: 69, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 280000, toh: null, poh: 55, vacant: null, avgRent2br: null, avgRent3br: null, notes: "3-park portfolio. 69 pads total, 55 POHs.", email: null, source: "Monday Leads" },
  { name: "Palm Harbour Estates Mobile Home & RV Park", parkNames: ["Palm Harbour Estates Mobile Home & RV Park"], city: "Tucson", state: "AZ", address: "1560 W Fort Lowell Rd, Tucson, AZ", totalLots: 69, price: 3500000, pricePerPad: 50725, lotRent: 607, medianHomePrice: null, toh: 69, poh: null, vacant: 2, avgRent2br: null, avgRent3br: null, notes: "69 total sites. All TOH. Premium park. Open to $3.5M offer.", email: null, source: "Monday Leads" },
  { name: "Sleepy Hollow MH Park", parkNames: ["Sleepy Hollow MH Park", "Green Acres"], city: "Dodge City", state: "KS", address: "908 Rath Ave, Dodge City, KS 67801", totalLots: 68, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 195000, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "2-park portfolio. Sleepy Hollow: city water/sewer. Green Acres: city water + lagoon.", email: null, source: "Monday Leads" },
  { name: "Meridian Cherry Lane", parkNames: ["Meridian Cherry Lane"], city: "Meridian", state: "ID", address: "314 West Cherry Lane, Meridian, ID", totalLots: 68, price: null, pricePerPad: null, lotRent: 575, medianHomePrice: 526971, toh: 68, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "68 lots, all occupied, all TOH. Lot rent $550-$600/mo. Open to selling. Median income: $96,361.", email: "spcady54@gmail.com", source: "Monday Leads" },
  { name: "Fortney Homes", parkNames: ["Fortney Homes"], city: "Hagerstown", state: "MD", address: "14243 Pennsylvania Ave, Hagerstown, MD 21742", totalLots: 67, price: 4500000, pricePerPad: 67164, lotRent: null, medianHomePrice: 337000, toh: null, poh: null, vacant: null, avgRent2br: null, avgRent3br: null, notes: "Owner: William E Pennington. 67 lots. Offered $60K/pad; seller says property has excess land for ~150% more homes.", email: "Meghan@forestdrivesp.com", source: "Monday Leads" },
  { name: "Brandon Mobile Home Park", parkNames: ["Brandon Mobile Home Park"], city: "Brandon", state: "MS", address: "450 Overby St, Brandon, MS 39042", totalLots: 67, price: 3350000, pricePerPad: 50000, lotRent: null, medianHomePrice: 279000, toh: null, poh: null, vacant: 1, avgRent2br: null, avgRent3br: null, notes: "Owner: Sara Cook. Lot rent $350-$550. POH rent $900-$1,200. Price ~$50K/pad.", email: "saracook2025@gmail.com", source: "Monday Leads" },
  { name: "Mount Joy MHP", parkNames: ["Mount Joy MHP"], city: "Davenport", state: "IA", address: "21445 Scott Park Road, Davenport, IA", totalLots: 66, price: 3800000, pricePerPad: 57576, lotRent: 410, medianHomePrice: 213527, toh: 66, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "66 lots, all TOH. Well and activated septic. Lot rent $410. Would consider selling at $3.8M. Median income: $73,682.", email: "bdpeete58@gmail.com", source: "Monday Leads" },
  { name: "Osceola Mobile Home Park", parkNames: ["Osceola Mobile Home Park"], city: "New Port Richey", state: "FL", address: "9821 Hopi Ln, New Port Richey, FL", totalLots: 65, price: null, pricePerPad: null, lotRent: 360, medianHomePrice: 373096, toh: null, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "65 total lots, no vacancies, mostly TOH. Lot rent $360/mo. Would consider an offer. Median income: $73,222.", email: null, source: "Monday Leads" },
  { name: "Garden City Mobile Home Park", parkNames: ["Garden City Mobile Home Park"], city: "Columbus", state: "IN", address: "926 Jonesville Road, Columbus, IN", totalLots: 55, price: null, pricePerPad: null, lotRent: 370, medianHomePrice: 272715, toh: 55, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "All TOH. In acquisition mode. Median income: $83,958.", email: null, source: "Monday Leads" },
  { name: "Countryside Village", parkNames: ["Countryside Village"], city: "Twin Falls", state: "ID", address: "1605 Grandview Drive NW, Twin Falls, ID", totalLots: 54, price: null, pricePerPad: null, lotRent: 485, medianHomePrice: 367714, toh: 54, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "54 lots, 100% occupied, all TOH. 55+ community. Lot rent $485/mo. Median income: $62,647.", email: "mbj@icon-media.com", source: "Monday Leads" },
  { name: "Oak Ridge MHP", parkNames: ["Oak Ridge MHP"], city: "Ridgeland", state: "SC", address: "700 N Green St, Ridgeland, SC 29936", totalLots: 54, price: 2750000, pricePerPad: 50926, lotRent: 400, medianHomePrice: 235000, toh: 54, poh: null, vacant: 3, avgRent2br: null, avgRent3br: null, notes: "All TOH. $400 lot rent. City water/sewer. Price $2.75M.", email: null, source: "Monday Leads" },
  { name: "Riverside Mobile Home Park", parkNames: ["Riverside Mobile Home Park"], city: "Hardeeville", state: "SC", address: "57 Riverside Dr, Hardeeville, SC 29927", totalLots: 53, price: null, pricePerPad: null, lotRent: 375, medianHomePrice: 430000, toh: 53, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "52 lots + 1 apartment. 100% occupied. All TOH. City water/sewer.", email: null, source: "Monday Leads" },
  { name: "Country Oaks Arbor Mobile Home Park", parkNames: ["Country Oaks Arbor Mobile Home Park"], city: "Manvel", state: "TX", address: "3318 Old Chocolate Bayou Rd, Manvel, TX", totalLots: 51, price: 4000000, pricePerPad: 78431, lotRent: 580, medianHomePrice: 436042, toh: 43, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "51 lots, 100% occupied. All TOH. Lot rent $580/mo. Wants $4M total. Median income: $132,571.", email: null, source: "Monday Leads" },
  { name: "Country Acres MHC", parkNames: ["Country Acres MHC"], city: "Yankton", state: "SD", address: "100 Par Ln, Yankton, SD 57078", totalLots: 50, price: null, pricePerPad: null, lotRent: 185, medianHomePrice: 268000, toh: 36, poh: null, vacant: 14, avgRent2br: null, avgRent3br: null, notes: "~36 occupied. Majority POH. County water/sewer. Lot rent $180-$190. POH rent $700-$1,300.", email: null, source: "Monday Leads" },
  { name: "Highland Park MHC", parkNames: ["Highland Park MHC"], city: "North Charleston", state: "SC", address: "6826 Rivers Ave, Charleston, SC 29406", totalLots: 45, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 280000, toh: 45, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "All TOH, all occupied. City water/sewer. Turned down $3M offer. May consider $3.2M.", email: null, source: "Monday Leads" },
  { name: "Washington Resort Trailer Park", parkNames: ["Washington Resort Trailer Park"], city: "Shawano", state: "WI", address: "W5035 Resort Road, Shawano, WI", totalLots: 44, price: null, pricePerPad: null, lotRent: 250, medianHomePrice: 238083, toh: 44, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "44 lots, all occupied, all TOH. City water and city sewer. Lot rent $250/mo. Median income: $64,643.", email: "krisrobaidek@gmail.com", source: "Monday Leads" },
  { name: "Sunny Meadows Mobile Home Park", parkNames: ["Sunny Meadows Mobile Home Park"], city: "Scottsburg", state: "IN", address: "251 S Lake Rd N, Scottsburg, IN 47170", totalLots: 41, price: 1200000, pricePerPad: 29268, lotRent: 305, medianHomePrice: 215000, toh: 36, poh: 5, vacant: null, avgRent2br: null, avgRent3br: null, notes: "Owners: Rick & Anne Mastain. 5 RTO POHs. Lot rent $305 + $80 utilities. Asking $1.2M. Rick's bottom is $2.4M.", email: "rickmastain@gmail.com", source: "Monday Leads" },
  { name: "Woodbine Oaks", parkNames: ["Woodbine Oaks"], city: "Butler", state: "PA", address: "539 Chicora Rd, Butler, PA 16001", totalLots: 38, price: 1050000, pricePerPad: 27632, lotRent: 435, medianHomePrice: 214000, toh: 31, poh: null, vacant: 7, avgRent2br: null, avgRent3br: null, notes: "31 occupied (all TOH). Own water system + septic. Owner Monty ready to sell. Asking $1.05M.", email: null, source: "Monday Leads" },
  { name: "Ardis MHP", parkNames: ["Ardis MHP"], city: "Hixson", state: "TN", address: "7019 Highway 153 Blvd, Hixson, TN", totalLots: 32, price: null, pricePerPad: null, lotRent: 350, medianHomePrice: null, toh: 32, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "32 sites, fully occupied, all TOH. Lot rent $350. City water & sewer. Holding for now.", email: "lynncenn905@aol.com", source: "Monday Leads" },
  { name: "Lake Shore Mobile Home Park", parkNames: ["Lake Shore Mobile Home Park"], city: "Grand Prairie", state: "TX", address: "2101 Hardy Road, Grand Prairie, TX 75051", totalLots: 32, price: 2000000, pricePerPad: 62500, lotRent: 650, medianHomePrice: 260000, toh: null, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "Owner: Ram Konara. 3 POHs being filled. City water/sewer. Asking $2M.", email: "Rkonara@yahoo.com", source: "Monday Leads" },
  { name: "Edgemont Mobile Home Park", parkNames: ["Edgemont Mobile Home Park"], city: "Wendell", state: "NC", address: "2081 Wendell Blvd, Wendell, NC 27591", totalLots: 31, price: null, pricePerPad: null, lotRent: 490, medianHomePrice: 380000, toh: 30, poh: null, vacant: 1, avgRent2br: null, avgRent3br: null, notes: "30 occupied. Avg lot rent ~$490. Well/septic - can connect to public water for $70K.", email: null, source: "Monday Leads" },
  { name: "Highland Heights Mobile Village", parkNames: ["Highland Heights Mobile Village"], city: "Sturgeon Bay", state: "WI", address: "1329 W Walnut Dr, Sturgeon Bay, WI", totalLots: 30, price: 2000000, pricePerPad: 66667, lotRent: 400, medianHomePrice: 378896, toh: 14, poh: 16, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "30 spaces, all occupied. 14 TOH, 16 POH. Lot rent $400/mo. POH rent $900/mo. Turned down $2M. Median income: $68,141.", email: "davedemmin@yahoo.com", source: "Monday Leads" },
  { name: "Congaree Village", parkNames: ["Congaree Village"], city: "West Columbia", state: "SC", address: "1535 Daniel Rd, West Columbia, SC 29170", totalLots: 30, price: 1200000, pricePerPad: 40000, lotRent: 540, medianHomePrice: 240000, toh: 22, poh: null, vacant: 8, avgRent2br: null, avgRent3br: null, notes: "22 occupied. City water & septic. Lot rent ~$525/mo.", email: null, source: "Monday Leads" },
  { name: "Williams Mobile Home Park", parkNames: ["Williams Mobile Home Park"], city: "Joppatowne", state: "MD", address: "578 Trimble Rd, Joppatowne, MD 21085", totalLots: 25, price: 4000000, pricePerPad: 160000, lotRent: 625, medianHomePrice: 371000, toh: 25, poh: null, vacant: 0, avgRent2br: null, avgRent3br: null, notes: "25 spaces, all occupied. $4M asking price.", email: null, source: "Monday Leads" },
  { name: "Skyline Park", parkNames: ["Skyline Park"], city: "Knoxville", state: "TN", address: "3167 Rifle Range Rd, Knoxville, TN 37918", totalLots: 19, price: 690000, pricePerPad: 36316, lotRent: 450, medianHomePrice: 295000, toh: 14, poh: null, vacant: 1, avgRent2br: null, avgRent3br: null, notes: "14 occupied (all TOH), 1 vacant.", email: null, source: "Monday Leads" },
  
  // ICE LISTINGS
  { name: "Shadow Lake Village", parkNames: ["Shadow Lake Village"], city: "Mason", state: "OH", address: "2479 North Mason Montgomery Road, Mason, OH 45040", totalLots: 300, price: 12000000, pricePerPad: 40000, lotRent: 400, medianHomePrice: 505000, toh: null, poh: null, vacant: null, avgRent2br: 1500, avgRent3br: 1850, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Sunnydale Mobile Home Community", parkNames: ["Sunnydale Mobile Home Community", "Eldorado Estates Mobile Home"], city: "St. Charles", state: "MO", address: "301 Sunnydale Dr, Saint Charles, MO 63301", totalLots: 697, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 308000, toh: null, poh: null, vacant: null, avgRent2br: 1050, avgRent3br: 1350, notes: "2-park portfolio. ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Trails End MHC", parkNames: ["Trails End MHC"], city: "Washington", state: "NC", address: "12 Trails End S, Washington, NC 27889", totalLots: 48, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 200000, toh: 48, poh: null, vacant: 0, avgRent2br: 850, avgRent3br: 1050, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Woodland Village RV/MH Park", parkNames: ["Woodland Village RV/MH Park"], city: "Portage", state: "IN", address: "5757 Melton Road, Portage, IN 46368", totalLots: 190, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 268000, toh: null, poh: null, vacant: null, avgRent2br: 1050, avgRent3br: 1300, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Acacia MHP", parkNames: ["Acacia MHP"], city: "Las Vegas", state: "NV", address: "1832 N Walnut Rd, Las Vegas, NV 89115", totalLots: 61, price: null, pricePerPad: null, lotRent: null, medianHomePrice: 323000, toh: 56, poh: null, vacant: 4, avgRent2br: 1200, avgRent3br: 1500, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Alta Vista Trailer Park", parkNames: ["Alta Vista Trailer Park"], city: "Henderson", state: "NV", address: "711 E Lake Mead Pkwy, Henderson, NV 89015", totalLots: 150, price: 25000000, pricePerPad: 166667, lotRent: 850, medianHomePrice: 350000, toh: 133, poh: 12, vacant: null, avgRent2br: 1300, avgRent3br: 1600, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Deerfield Estates", parkNames: ["Deerfield Estates"], city: "Flat Rock", state: "MI", address: "26211 Telegraph Rd, Flat Rock, MI 48134", totalLots: 820, price: 123000000, pricePerPad: 150000, lotRent: 600, medianHomePrice: 256000, toh: 788, poh: 20, vacant: null, avgRent2br: 1100, avgRent3br: 1350, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Casa Linda Republic", parkNames: ["Casa Linda Republic"], city: "Las Vegas", state: "NV", address: "5250 E Lake Mead Blvd, Las Vegas, NV", totalLots: 107, price: 11500000, pricePerPad: 107477, lotRent: 790, medianHomePrice: 356132, toh: 102, poh: 2, vacant: null, avgRent2br: null, avgRent3br: null, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
  { name: "Stahla Mobile Home Park", parkNames: ["Stahla Mobile Home Park"], city: "Lexington", state: "NE", address: "Rimpley Ln, Lexington, NE", totalLots: 36, price: 1000000, pricePerPad: 27778, lotRent: 226, medianHomePrice: 204384, toh: 33, poh: 3, vacant: null, avgRent2br: null, avgRent3br: null, notes: "ICE listing.", email: null, source: "Monday Leads ICE" },
]

// Total count helper
export const TOTAL_LEADS = MONDAY_LEADS.length
